/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lt_terzer_Libwdi */

#ifndef _Included_lt_terzer_Libwdi
#define _Included_lt_terzer_Libwdi
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     lt_terzer_Libwdi
	 * Method:    installDriver
	 * Signature: (II)I
	 */
	JNIEXPORT jint JNICALL Java_lt_terzer_Libwdi_installDriver__II
	(JNIEnv*, jclass, jint, jint);

	/*
	 * Class:     lt_terzer_Libwdi
	 * Method:    installDriver
	 * Signature: (III)I
	 */
	JNIEXPORT jint JNICALL Java_lt_terzer_Libwdi_installDriver__III
	(JNIEnv*, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
